name: Danger

on: [pull_request]

jobs:
  danger:
    name: Danger
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: install danger-JS
        run: |
          npm install -g danger
      - name: Run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls
          cd Danger
          swift run danger-swift ci
