name: docc

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: make directory docs/
        run: |
          mkdir -p docs/ParchmentCore
          mkdir -p docs/Parchment
      - name: run generate-documentation for ParchmentCore
        run: swift package --allow-writing-to-directory docs/ParchmentCore
          generate-documentation --target ParchmentCore
          --disable-indexing
          --transform-for-static-hosting
          --hosting-base-path Parchment-swift/ParchmentCore
          --output-path docs/ParchmentCore
      - name: run generate-documentation for Parchment
        run: swift package --allow-writing-to-directory docs/Parchment
          generate-documentation --target Parchment
          --disable-indexing
          --transform-for-static-hosting
          --hosting-base-path Parchment-swift/Parchment
          --output-path docs/Parchment
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
